ktor:
    deployment:
        port: 8080

    application:
        modules:
            - org.jetbrains.kotlinconf.backend.DiModuleKt.diModule
            - org.jetbrains.kotlinconf.backend.PluginsModuleKt.pluginsSetup
            - org.jetbrains.kotlinconf.backend.RoutesModuleKt.routesModule


sessionize:
    url: "https://sessionize.com/api/v2/oleuq4yu/view/All"
    imagesUrl: "https://sessionize.com/image/"
    interval: 60

news:
    repo: "JetBrains/kotlinconf-app"
    branch: "main"
    folder: "news"

database:
    host: "$DB0_HOST:"
    user: "$DB0_USERNAME:"
    password: "$DB0_PASSWORD:"
    database: "$DB0_NAME:"

    poolSize: 5

service:
    environment: production
    secret: "$ADMIN_SECRET:test"
