name: Build all apps
on:
  pull_request:
  push:
    branches:
      - amper

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-jvm:
    name: Build desktop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Assemble desktop jar
        run: ./amper build -m jvmApp

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Android debug build
        run: ./amper build -m androidApp

  build-ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      - name: iOS debug build
        run: ./amper build -m iosApp -p iosArm64

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build backend jar
        run: ./amper build -m backend
